// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB062NIUVFSbrRm3B7LEj0gQqJC_5z2n-Y',
    appId: '1:841394497319:web:c692a685b6000661bceb02',
    messagingSenderId: '841394497319',
    projectId: 'qr-scanner-app-dae8e',
    authDomain: 'qr-scanner-app-dae8e.firebaseapp.com',
    storageBucket: 'qr-scanner-app-dae8e.firebasestorage.app',
    measurementId: 'G-HD4RLZ465H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPh18vfxjqgGffUJOHkDdNQ4XLDvMqRkw',
    appId: '1:592026459872:android:e804edf5ca2c6b6840fa85',
    messagingSenderId: '592026459872',
    projectId: 'qr-scanner-app-716a2',
    storageBucket: 'qr-scanner-app-716a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzITORuY0vy4b62ppnvg0HC96w4CMSS20',
    appId: '1:592026459872:ios:ba8687e08c9361f240fa85',
    messagingSenderId: '592026459872',
    projectId: 'qr-scanner-app-716a2',
    storageBucket: 'qr-scanner-app-716a2.firebasestorage.app',
    iosBundleId: 'com.example.qrScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzITORuY0vy4b62ppnvg0HC96w4CMSS20',
    appId: '1:592026459872:ios:ba8687e08c9361f240fa85',
    messagingSenderId: '592026459872',
    projectId: 'qr-scanner-app-716a2',
    storageBucket: 'qr-scanner-app-716a2.firebasestorage.app',
    iosBundleId: 'com.example.qrScannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB062NIUVFSbrRm3B7LEj0gQqJC_5z2n-Y',
    appId: '1:841394497319:web:ea26b7d1214ddf4dbceb02',
    messagingSenderId: '841394497319',
    projectId: 'qr-scanner-app-dae8e',
    authDomain: 'qr-scanner-app-dae8e.firebaseapp.com',
    storageBucket: 'qr-scanner-app-dae8e.firebasestorage.app',
    measurementId: 'G-S3B6Y8G91T',
  );
}